# Generated by Django 4.1.4 on 2022-12-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='months',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('batch', models.CharField(choices=[('6-7AM', '6-7AM'), ('7-8AM', '7-8AM'), ('8-9AM', '8-9AM'), ('5-6PM', '5-6PM')], max_length=5)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.CharField(default=500, editable=False, max_length=3)),
                ('paid_month', models.CharField(default='December', max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.months')),
            ],
        ),
    ]
