# Generated by Django 4.1.4 on 2022-12-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='month',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='myapp.months'),
        ),
    ]
