# Generated by Django 4.1.4 on 2022-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid',
            field=models.BooleanField(default='False'),
        ),
    ]
